import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs=[]; p.on('pageerror', e=>errs.push(e.message));
await p.goto('http://localhost:3000');
await p.fill('#nameIn','Tester'); await p.click('text=Continue →');
await p.waitForSelector('#lobbyScreen.active');
await p.click('text=Create New Room');
await p.waitForSelector('#waitingScreen.active');
await p.click('text=Leave Room');
await p.waitForTimeout(500);
console.log('A) leave waiting → lobby:', await p.evaluate(()=>document.getElementById('lobbyScreen').classList.contains('active')));
await p.click('text=Create New Room');
await p.waitForSelector('#waitingScreen.active');
await p.click('#startBtn');
await p.waitForTimeout(2500);
await p.click('#leaveBtn'); await p.waitForTimeout(300);
console.log('B) leave btn opens popup:', await p.evaluate(()=>document.getElementById('leaveOvl').style.display==='block'));
await p.screenshot({ path:'/tmp/leave_popup.png' });
await p.click('text=Keep playing'); await p.waitForTimeout(200);
console.log('C) keep playing stays in game:', await p.evaluate(()=>document.getElementById('gameScreen').classList.contains('active') && document.getElementById('leaveOvl').style.display==='none'));
await p.click('#leaveBtn'); await p.waitForTimeout(200);
await p.click('text=Yes, leave'); await p.waitForTimeout(600);
console.log('D) yes leave → lobby:', await p.evaluate(()=>document.getElementById('lobbyScreen').classList.contains('active')));
console.log('errors:', errs);
await b.close();
